#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
# dunst &
# polybar &
# picom --config $HOME/.config/picom/picom.conf &

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d I II III IV V VI VII VIII IX X
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="eDP"
	EXTERNAL_MONITOR="HDMI-A-0"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d I III V VII IX
		bspc monitor "$INTERNAL_MONITOR" -d II IV VI VIII X
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d I II III IV V VI VII VIII IX X
	fi
}

## Three Monitors Setup (Laptop and two external monitor, 3-2-3 workspaces)
three_monitors_workspaces() {
	# again, change these values accordingly
	MONITOR_1="eDP"
	MONITOR_2="HDMI-A-0"
	MONITOR_3="HDMI-A-1"
	bspc monitor "$MONITOR_1" -d I III
	bspc monitor "$MONITOR_2" -d II IV VI
	bspc monitor "$MONITOR_3" -d V VII X
	bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

## Uncomment only one function according to your needs
default_workspaces
#two_monitors_workspaces
#three_monitors_workspaces

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#313244"
bspc config focused_border_color "#cba6f7"
bspc config presel_feedback_color "#cba6f7"

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config presel_feedback true


## Window rules ----------------------------------------------#

# Fix cursor
xsetroot -cursor_name left_ptr &
