#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
##
## Default Setup (Set 8 workspaces on each monitor)
default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="eDP"
	EXTERNAL_MONITOR="HDMI-A-0"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '1' '3' '5' '7' '9'
		bspc monitor "$INTERNAL_MONITOR" -d '2' '4' '6' '8' '0'
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'
	fi
}

## Three Monitors Setup (Laptop and two external monitor, 3-2-3 workspaces)
three_monitors_workspaces() {
	# again, change these values accordingly
	MONITOR_1="eDP"
	MONITOR_2="HDMI-A-0"
	MONITOR_3="HDMI-A-1"
	bspc monitor "$MONITOR_1" -d '1' '3'
	bspc monitor "$MONITOR_2" -d '2' '4' '6'
	bspc monitor "$MONITOR_3" -d '5' '7' '0'
	bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

## Uncomment only one function according to your needs
default_workspaces
#two_monitors_workspaces
#three_monitors_workspaces

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#313244"
bspc config focused_border_color "#cba6f7"
bspc config presel_feedback_color "#cba6f7"

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Window rules ----------------------------------------------#

## remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
bspc rule -a Alacritty desktop='^1' follow=on focus=on

sxhkd &
dunst &
polybar &
picom --config $HOME/.config/picom/picom.conf &
setxkbmap -layout us -variant intl
