#! /bin/sh

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
export EDITOR='nvim'
export TERMINAL='kitty'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# Default 1 monitor with 6 workspaces
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'
done

bspc config border_width            2
bspc config window_gap              3
bspc config normal_border_color     "#313244"
bspc config focused_border_color    "#cba6f7"
bspc config presel_feedback_color   "#cba6f7"

bspc config split_ratio             0.51
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config presel_feedback         true

# picture-in-picture floating
bspc rule -a '*:*:Picture-in-Picture' state=floating

# Set default desktop for kitty
bspc rule -a kitty desktop='^1' focus=on

# --------------------------------------------------

# Fix cursor
xsetroot -cursor_name left_ptr &

# Select keyboard layout
setxkbmap -layout us -variant intl &

# Wallpaper
nitrogen --restore &

# Set resolution
xrandr -s 1920x1080 &

# Verifica se o sxhkd está rodando, se não estiver, inicia
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/sxhkd/sxhkdrc & }

# Launch picom
pidof -q picom || { picom --config "${HOME}"/.config/picom/picom.conf & }
